// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShope.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310234350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "New York",
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Phone = "770100111",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Los Angeles",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "770100222",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Chicago",
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Phone = "770100333",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Houston",
                            Email = "emma@example.com",
                            FirstName = "Emma",
                            LastName = "Davis",
                            Phone = "770100444",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Philadelphia",
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            Phone = "770100555",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        });
                });

            modelBuilder.Entity("SmartShope.Entities.AccountStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("AccountStatements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 24, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5492),
                            CustomerId = 1,
                            Description = "January Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5523),
                            CustomerId = 1,
                            Description = "February Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 27, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5528),
                            CustomerId = 2,
                            Description = "January Purchases",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 3, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5533),
                            CustomerId = 3,
                            Description = "February Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 4, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5537),
                            CustomerId = 4,
                            Description = "March Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5541),
                            CustomerId = 5,
                            Description = "March Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 756, DateTimeKind.Local).AddTicks(5546),
                            CustomerId = 5,
                            Description = "March Purchases",
                            IsClosed = true,
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("SmartShope.Entities.DebtPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountStatementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountStatementID");

                    b.ToTable("DebtPages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatementID = 1,
                            CreatedAt = new DateTime(2026, 2, 24, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2847),
                            Description = "Page 1 - Vegetables",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 2,
                            AccountStatementID = 1,
                            CreatedAt = new DateTime(2026, 2, 24, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2862),
                            Description = "Page 2 - Beverages",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 3,
                            AccountStatementID = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2867),
                            Description = "Page 1 - Snacks",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 4,
                            AccountStatementID = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2871),
                            Description = "Page 2 - Dairy",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 5,
                            AccountStatementID = 3,
                            CreatedAt = new DateTime(2026, 2, 27, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2876),
                            Description = "Page 1 - Household Items",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            Id = 6,
                            AccountStatementID = 3,
                            CreatedAt = new DateTime(2026, 2, 27, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2880),
                            Description = "Page 2 - Cleaning Supplies",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            Id = 7,
                            AccountStatementID = 4,
                            CreatedAt = new DateTime(2026, 3, 3, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2885),
                            Description = "Page 1 - Fruits",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 8,
                            AccountStatementID = 4,
                            CreatedAt = new DateTime(2026, 3, 3, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2889),
                            Description = "Page 2 - Vegetables",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 9,
                            AccountStatementID = 5,
                            CreatedAt = new DateTime(2026, 3, 4, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2893),
                            Description = "Page 1 - Snacks",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 10,
                            AccountStatementID = 5,
                            CreatedAt = new DateTime(2026, 3, 4, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2897),
                            Description = "Page 2 - Beverages",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 11,
                            AccountStatementID = 6,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2901),
                            Description = "Page 1 - Dairy",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 12,
                            AccountStatementID = 6,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2906),
                            Description = "Page 2 - Fruits",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 13,
                            AccountStatementID = 7,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2910),
                            Description = "Page 1 - Dairy",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            Id = 14,
                            AccountStatementID = 7,
                            CreatedAt = new DateTime(2026, 3, 6, 2, 43, 49, 758, DateTimeKind.Local).AddTicks(2914),
                            Description = "Page 2 - Fruits",
                            IsClosed = true,
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("SmartShope.Entities.StatementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DebtPageId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity] * [Price]");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DebtPageId");

                    b.ToTable("StatementItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DebtPageId = 1,
                            ItemName = "Potatoes",
                            Price = 2m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            DebtPageId = 1,
                            ItemName = "Carrots",
                            Price = 1.5m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            DebtPageId = 1,
                            ItemName = "Tomatoes",
                            Price = 2.2m,
                            Quantity = 4,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            DebtPageId = 2,
                            ItemName = "Mineral Water",
                            Price = 0.5m,
                            Quantity = 12,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            Id = 5,
                            DebtPageId = 2,
                            ItemName = "Orange Juice",
                            Price = 1.2m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            Id = 6,
                            DebtPageId = 3,
                            ItemName = "Chips",
                            Price = 2m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            Id = 7,
                            DebtPageId = 3,
                            ItemName = "Cookies",
                            Price = 3m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            Id = 8,
                            DebtPageId = 4,
                            ItemName = "Milk",
                            Price = 1.5m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 9,
                            DebtPageId = 4,
                            ItemName = "Cheese",
                            Price = 5m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 10,
                            DebtPageId = 5,
                            ItemName = "Pan",
                            Price = 20m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 11,
                            DebtPageId = 5,
                            ItemName = "Pressure Cooker",
                            Price = 35m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 12,
                            DebtPageId = 6,
                            ItemName = "Soap",
                            Price = 1.2m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 13,
                            DebtPageId = 6,
                            ItemName = "Detergent",
                            Price = 6m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            Id = 14,
                            DebtPageId = 7,
                            ItemName = "Apple",
                            Price = 2m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 15,
                            DebtPageId = 7,
                            ItemName = "Banana",
                            Price = 1.8m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 16,
                            DebtPageId = 8,
                            ItemName = "Cucumber",
                            Price = 1.5m,
                            Quantity = 4,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 17,
                            DebtPageId = 8,
                            ItemName = "Lettuce",
                            Price = 1.2m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 18,
                            DebtPageId = 9,
                            ItemName = "Chocolate",
                            Price = 1.5m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 19,
                            DebtPageId = 9,
                            ItemName = "Candy",
                            Price = 2.5m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            Id = 20,
                            DebtPageId = 10,
                            ItemName = "Cola",
                            Price = 1m,
                            Quantity = 12,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            Id = 21,
                            DebtPageId = 10,
                            ItemName = "Orange Soda",
                            Price = 1.2m,
                            Quantity = 8,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            Id = 22,
                            DebtPageId = 11,
                            ItemName = "Yogurt",
                            Price = 0.8m,
                            Quantity = 10,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 23,
                            DebtPageId = 11,
                            ItemName = "Butter",
                            Price = 4m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 24,
                            DebtPageId = 12,
                            ItemName = "Mango",
                            Price = 3m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 25,
                            DebtPageId = 12,
                            ItemName = "Pineapple",
                            Price = 2.5m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            Id = 26,
                            DebtPageId = 12,
                            ItemName = "Mango",
                            Price = 3m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 27,
                            DebtPageId = 12,
                            ItemName = "Pineapple",
                            Price = 2.5m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Piece"
                        });
                });

            modelBuilder.Entity("SmartShope.Entities.AccountStatement", b =>
                {
                    b.HasOne("Domain.Customer", "Customer")
                        .WithMany("AccountStatements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartShope.Entities.DebtPage", b =>
                {
                    b.HasOne("SmartShope.Entities.AccountStatement", "AccountStatement")
                        .WithMany("DebtPages")
                        .HasForeignKey("AccountStatementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatement");
                });

            modelBuilder.Entity("SmartShope.Entities.StatementItem", b =>
                {
                    b.HasOne("SmartShope.Entities.DebtPage", "DebtPage")
                        .WithMany("StatementItems")
                        .HasForeignKey("DebtPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtPage");
                });

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Navigation("AccountStatements");
                });

            modelBuilder.Entity("SmartShope.Entities.AccountStatement", b =>
                {
                    b.Navigation("DebtPages");
                });

            modelBuilder.Entity("SmartShope.Entities.DebtPage", b =>
                {
                    b.Navigation("StatementItems");
                });
#pragma warning restore 612, 618
        }
    }
}
