// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317120102_Entiteis Id Names Changed")]
    partial class EntiteisIdNamesChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AccountStatement", b =>
                {
                    b.Property<int>("AccountStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountStatementId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("AccountStatementId");

                    b.HasIndex("CustomerId");

                    b.ToTable("AccountStatements", (string)null);

                    b.HasData(
                        new
                        {
                            AccountStatementId = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5869),
                            CustomerId = 1,
                            Description = "January Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            AccountStatementId = 2,
                            CreatedAt = new DateTime(2026, 3, 7, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5886),
                            CustomerId = 1,
                            Description = "February Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            AccountStatementId = 3,
                            CreatedAt = new DateTime(2026, 3, 5, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5888),
                            CustomerId = 2,
                            Description = "January Purchases",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            AccountStatementId = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5890),
                            CustomerId = 3,
                            Description = "February Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            AccountStatementId = 5,
                            CreatedAt = new DateTime(2026, 3, 10, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5891),
                            CustomerId = 4,
                            Description = "March Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            AccountStatementId = 6,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5893),
                            CustomerId = 5,
                            Description = "March Purchases",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            AccountStatementId = 7,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 617, DateTimeKind.Local).AddTicks(5895),
                            CustomerId = 5,
                            Description = "March Purchases",
                            IsClosed = true,
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "New York",
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Phone = "770100111",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Los Angeles",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "770100222",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Chicago",
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            LastName = "Brown",
                            Phone = "770100333",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Houston",
                            Email = "emma@example.com",
                            FirstName = "Emma",
                            LastName = "Davis",
                            Phone = "770100444",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Philadelphia",
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            Phone = "770100555",
                            SecondName = "Ali",
                            ThirdName = "Ahmed"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DebtPage", b =>
                {
                    b.Property<int>("DebtPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DebtPageId"));

                    b.Property<int>("AccountStatementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("NVARCHAR");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("DebtPageId");

                    b.HasIndex("AccountStatementID");

                    b.ToTable("DebtPages", (string)null);

                    b.HasData(
                        new
                        {
                            DebtPageId = 1,
                            AccountStatementID = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2596),
                            Description = "Page 1 - Vegetables",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 2,
                            AccountStatementID = 1,
                            CreatedAt = new DateTime(2026, 3, 2, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2603),
                            Description = "Page 2 - Beverages",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 3,
                            AccountStatementID = 2,
                            CreatedAt = new DateTime(2026, 3, 7, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2605),
                            Description = "Page 1 - Snacks",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 4,
                            AccountStatementID = 2,
                            CreatedAt = new DateTime(2026, 3, 7, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2607),
                            Description = "Page 2 - Dairy",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 5,
                            AccountStatementID = 3,
                            CreatedAt = new DateTime(2026, 3, 5, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2609),
                            Description = "Page 1 - Household Items",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            DebtPageId = 6,
                            AccountStatementID = 3,
                            CreatedAt = new DateTime(2026, 3, 5, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2610),
                            Description = "Page 2 - Cleaning Supplies",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            DebtPageId = 7,
                            AccountStatementID = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2612),
                            Description = "Page 1 - Fruits",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 8,
                            AccountStatementID = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2614),
                            Description = "Page 2 - Vegetables",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 9,
                            AccountStatementID = 5,
                            CreatedAt = new DateTime(2026, 3, 10, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2616),
                            Description = "Page 1 - Snacks",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 10,
                            AccountStatementID = 5,
                            CreatedAt = new DateTime(2026, 3, 10, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2617),
                            Description = "Page 2 - Beverages",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 11,
                            AccountStatementID = 6,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2619),
                            Description = "Page 1 - Dairy",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 12,
                            AccountStatementID = 6,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2620),
                            Description = "Page 2 - Fruits",
                            IsClosed = false,
                            IsPaid = false
                        },
                        new
                        {
                            DebtPageId = 13,
                            AccountStatementID = 7,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2622),
                            Description = "Page 1 - Dairy",
                            IsClosed = true,
                            IsPaid = true
                        },
                        new
                        {
                            DebtPageId = 14,
                            AccountStatementID = 7,
                            CreatedAt = new DateTime(2026, 3, 12, 15, 1, 1, 618, DateTimeKind.Local).AddTicks(2624),
                            Description = "Page 2 - Fruits",
                            IsClosed = true,
                            IsPaid = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.StatementItem", b =>
                {
                    b.Property<int>("StatementItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatementItemId"));

                    b.Property<int>("DebtPageId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[Quantity] * [Price]");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatementItemId");

                    b.HasIndex("DebtPageId");

                    b.ToTable("StatementItems", (string)null);

                    b.HasData(
                        new
                        {
                            StatementItemId = 1,
                            DebtPageId = 1,
                            ItemName = "Potatoes",
                            Price = 2m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 2,
                            DebtPageId = 1,
                            ItemName = "Carrots",
                            Price = 1.5m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 3,
                            DebtPageId = 1,
                            ItemName = "Tomatoes",
                            Price = 2.2m,
                            Quantity = 4,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 4,
                            DebtPageId = 2,
                            ItemName = "Mineral Water",
                            Price = 0.5m,
                            Quantity = 12,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            StatementItemId = 5,
                            DebtPageId = 2,
                            ItemName = "Orange Juice",
                            Price = 1.2m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            StatementItemId = 6,
                            DebtPageId = 3,
                            ItemName = "Chips",
                            Price = 2m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            StatementItemId = 7,
                            DebtPageId = 3,
                            ItemName = "Cookies",
                            Price = 3m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            StatementItemId = 8,
                            DebtPageId = 4,
                            ItemName = "Milk",
                            Price = 1.5m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 9,
                            DebtPageId = 4,
                            ItemName = "Cheese",
                            Price = 5m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 10,
                            DebtPageId = 5,
                            ItemName = "Pan",
                            Price = 20m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 11,
                            DebtPageId = 5,
                            ItemName = "Pressure Cooker",
                            Price = 35m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 12,
                            DebtPageId = 6,
                            ItemName = "Soap",
                            Price = 1.2m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 13,
                            DebtPageId = 6,
                            ItemName = "Detergent",
                            Price = 6m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            StatementItemId = 14,
                            DebtPageId = 7,
                            ItemName = "Apple",
                            Price = 2m,
                            Quantity = 6,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 15,
                            DebtPageId = 7,
                            ItemName = "Banana",
                            Price = 1.8m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 16,
                            DebtPageId = 8,
                            ItemName = "Cucumber",
                            Price = 1.5m,
                            Quantity = 4,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 17,
                            DebtPageId = 8,
                            ItemName = "Lettuce",
                            Price = 1.2m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 18,
                            DebtPageId = 9,
                            ItemName = "Chocolate",
                            Price = 1.5m,
                            Quantity = 5,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 19,
                            DebtPageId = 9,
                            ItemName = "Candy",
                            Price = 2.5m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Box"
                        },
                        new
                        {
                            StatementItemId = 20,
                            DebtPageId = 10,
                            ItemName = "Cola",
                            Price = 1m,
                            Quantity = 12,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            StatementItemId = 21,
                            DebtPageId = 10,
                            ItemName = "Orange Soda",
                            Price = 1.2m,
                            Quantity = 8,
                            Total = 0m,
                            Unit = "Bottle"
                        },
                        new
                        {
                            StatementItemId = 22,
                            DebtPageId = 11,
                            ItemName = "Yogurt",
                            Price = 0.8m,
                            Quantity = 10,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 23,
                            DebtPageId = 11,
                            ItemName = "Butter",
                            Price = 4m,
                            Quantity = 1,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 24,
                            DebtPageId = 12,
                            ItemName = "Mango",
                            Price = 3m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 25,
                            DebtPageId = 12,
                            ItemName = "Pineapple",
                            Price = 2.5m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Piece"
                        },
                        new
                        {
                            StatementItemId = 26,
                            DebtPageId = 12,
                            ItemName = "Mango",
                            Price = 3m,
                            Quantity = 3,
                            Total = 0m,
                            Unit = "Kg"
                        },
                        new
                        {
                            StatementItemId = 27,
                            DebtPageId = 12,
                            ItemName = "Pineapple",
                            Price = 2.5m,
                            Quantity = 2,
                            Total = 0m,
                            Unit = "Piece"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AccountStatement", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany("AccountStatements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.DebtPage", b =>
                {
                    b.HasOne("Domain.Entities.AccountStatement", "AccountStatement")
                        .WithMany("DebtPages")
                        .HasForeignKey("AccountStatementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatement");
                });

            modelBuilder.Entity("Domain.Entities.StatementItem", b =>
                {
                    b.HasOne("Domain.Entities.DebtPage", "DebtPage")
                        .WithMany("StatementItems")
                        .HasForeignKey("DebtPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebtPage");
                });

            modelBuilder.Entity("Domain.Entities.AccountStatement", b =>
                {
                    b.Navigation("DebtPages");
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Navigation("AccountStatements");
                });

            modelBuilder.Entity("Domain.Entities.DebtPage", b =>
                {
                    b.Navigation("StatementItems");
                });
#pragma warning restore 612, 618
        }
    }
}
